### PR TITLE
Split recipes into three pages: parsing, generating, filtering

### PR DESCRIPTION
**Pull request by BurdetteLamar**

### CODE REVIEW

**Comment by BurdetteLamar** [comment]
@kou, can I merge this?

**Comment by kou** [comment]
No.
We should not merge with any CI failures.

**Comment by BurdetteLamar** [comment]
Ok

**Comment by kou** [comment]
Fixed.

**Comment by BurdetteLamar** [comment]
@kou, Oh, wow.  Sorry.   And thanks.

**Pull request merged**
