### PR TITLE
Enhanced Rdoc for CSV

### PR DESCRIPTION
**Pull request by BurdetteLamar**
I've begun working on enhanced rdoc for CSV.  Mostly, I'm interested in adding example code, beginning with the options.

I'm creating this PR to give The Powers That Be a chance to warn me if they are not interested in this work.

### CODE REVIEW

**Comment by kou** [comment]
Thanks.
I've added support for generating RDoc by Rake on master.
Could you rebase on master when this is ready to be reviewed?

**Comment by BurdetteLamar** [comment]
13/21 options done, + a few odds and ends.  For me, git rebase is deep and dark.  Can I save my files, make a new fork/clone, then restore my files?  Does that work?

Oh, and thanks for your interest.

**Comment by kou** [comment]
OK.
I'll do it. Please notify me when you complete this.

**Comment by BurdetteLamar** [comment]
I think this is good enough for you to look at.
- This has few changes outside of options.  (Other stuff later.)
- I used #fetch, not #[] to show the option defaults, b/c it gives an error if not found.
- The options are in the order you already had (I think).

**Comment by BurdetteLamar** [comment]
@kou, the tests did not work on my machine.  Old error, I think.  I ran 'rake test'.

**Comment by BurdetteLamar** [comment]
A few more things to do for options.

**Comment by BurdetteLamar** [comment]
@kou, ready when you are.

**Comment by BurdetteLamar** [comment]
Back to draft; working on converters.

**Comment by BurdetteLamar** [comment]
@kou, ready for you.  I will not push anything more (except very minor corrections) until we've had a chance to begin review/remark/rework/repush.  Suggest we do this piecemeal, maybe beginning with one or two options at a time?

**Comment by kou** [comment]
I've rebased and reverted code changes. Because the code changes break our CI.

It was good that we create a pull request per option but we already did for many options.
I couldn't review this large change. I'll merge this time.
We can improve documents we added as follow-up pull requests.

**Pull request merged**
