### PR TITLE
Use memoized parser_enumerator directly instead of assigning to variable

### PR DESCRIPTION
**Pull request by sampatbadhe**
Use memoized parser_enumerator directly instead of assigning to variable

### CODE REVIEW

**Comment by kou** [comment]
Why?

**Comment by sampatbadhe** [comment]
`parser_enumerator` is already memoized, so I feel no need to assign `parser_enumerator` to any variable to use.

**Comment by kou** [comment]
I want to avoid method calls as much as possible here.

**Comment by sampatbadhe** [comment]
sure @kou :+1: 
I'll close this PR.

**Pull request closed without merging**
