### PR TITLE
ci: test on maintained ruby versions

### PR DESCRIPTION
**Pull request by igas**

### CODE REVIEW

**Comment by kou** [comment]
Why? We want to support Ruby 2.5.0 or later as much as possible.
https://github.com/ruby/csv/blob/master/csv.gemspec#L57

**Comment by igas** [comment]
@kou because they are EOL, but I'm happy to just add 3.2. Should I restore 2.x?

**Comment by olleolleolle** [comment]
👋 [Rdoc](https://github.com/ruby/rdoc/blob/master/.github/workflows/test.yml#L9) uses an Action from the https://github.com/ruby/actions repo. It's pretty neat. That way, small edits to CI configuration are often automatic.

**Comment by igas** [comment]
Nice one @olleolleolle! Happy to switch to it, I guess we just need to agree if we support EOL ruby versions with security vulnerabilities.

**Comment by kou** [comment]
> Should I restore 2.x?

Yes.

> Happy to switch to it

I don't object it.

**Comment by kou** [comment]
I close this in favor of #289.

**Pull request closed without merging**
