### PR TITLE
test: rename Helper to CSVHelper

### PR DESCRIPTION
**Pull request by luke-gru**
Rename it so that in ruby/ruby, the generic name Helper is not used.

### CODE REVIEW

**Comment by luke-gru** [comment]
I'm assuming changes to this repo are ported over to ruby/ruby, right?

**Comment by kou** [comment]
> I'm assuming changes to this repo are ported over to ruby/ruby, right?

Right. But it's a manual operation.
Do you want this in ruby/ruby right now?

**Comment by luke-gru** [comment]
No, take your time there's no rush.

**Comment by kou** [comment]
I see.
I'll sync it to ruby/ruby when we release a new version or the next Ruby preview release.

**Pull request merged**
