### PR TITLE
Improve CSV performance

### PR DESCRIPTION
**Pull request by Watson1978**
https://github.com/ruby/ruby/pull/1842

If it will not use special variables (like $1, $&, $`...),
it can improve the performance by using Regexp#match? or String#match? instead of Regexp#=~ or String#=~.

## Environment
* OS : Ubuntu 17.10
* Compiler : gcc version 7.2.0
* CPU : Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
* Memory : 16 GB

## TL;DR
Methods     | Before | After  | Speed up
----------- | ------ | ------ | --------
CSV.foreach | 44.825 | 48.201 | 7.5%
CSV#shift   | 45.200 | 49.584 | 9.7%
CSV.read    | 42.968 | 46.853 | 9.0%
CSV.table   | 10.933 | 11.277 | 3.1%

## Before
```
Calculating -------------------------------------
         CSV.foreach     44.825  (± 0.0%) i/s -    228.000  in   5.086576s
           CSV#shift     45.200  (± 0.0%) i/s -    228.000  in   5.044297s
            CSV.read     42.968  (± 0.0%) i/s -    216.000  in   5.027504s
           CSV.table     10.933  (± 0.0%) i/s -     55.000  in   5.031098s
```

## After
```
Calculating -------------------------------------
         CSV.foreach     48.201  (± 0.0%) i/s -    244.000  in   5.062256s
           CSV#shift     49.584  (± 0.0%) i/s -    248.000  in   5.001652s
            CSV.read     46.853  (± 0.0%) i/s -    236.000  in   5.037044s
           CSV.table     11.277  (± 0.0%) i/s -     57.000  in   5.054694s
```

## Benchmark code
```ruby
require 'csv'
require 'benchmark/ips'

CSV.open("/tmp/file.csv", "w") do |csv|
  csv << ["player", "gameA", "gameB"]
  1000.times do
    csv << ['"Alice"', "84.0", "79.5"]
    csv << ['"Bob"', "20.0", "56.5"]
  end
end

Benchmark.ips do |x|
  x.report "CSV.foreach" do
    CSV.foreach("/tmp/file.csv") do |row|
    end
  end

  x.report "CSV#shift" do
    CSV.open("/tmp/file.csv") do |csv|
      while line = csv.shift
      end
    end
  end

  x.report "CSV.read" do
    CSV.read("/tmp/file.csv")
  end

  x.report "CSV.table" do
    CSV.table("/tmp/file.csv")
  end
end
```

### CODE REVIEW

**Comment by kou** [comment]
Can you include the benchmark script?

**Comment by Watson1978** [comment]
Hmm, CI has performed tests on Ruby 2.3.6. 
Regexp#match? and String#match? were introduced at Ruby 2.4.0 :(

**Comment by kou** [comment]
How about using refinements?

```ruby
unless String.method_defined?(:match?)
  module CSV
    module MatchP
      refine String do
        def match?(pattern)
          pattern === self
        end
      end
    end

    refine Regexp do
      def match?(string)
        self === string
      end
    end
  end

  using CSV::MatchP
end

# ...
```

If it doesn't any negative result on Ruby 2.3, 2.4, 2.5 and trunk, we can merge this safely.

**Comment by Watson1978** [comment]
@kou I added workaround by your idea to solve Ruby 2.3 issue. Thank you.

**Comment by kou** [comment]
Can you show benchmark result on Ruby 2.3 and trunk?
If this change sill faster on trunk and not changed on Ruby 2.3, I'll merge this.

**Comment by Watson1978** [comment]
OK, I took a benchmark result.
Seems there is no performance regression for Ruby 2.3.
(The original data is in https://gist.github.com/Watson1978/323367e52db63b8ab8ec46152a4b8390)

## Ruby 2.5.1
  | Before | After | Speed up
-- | -- | -- | --
CSV.foreach | 44.641 | 47.635 | 6.7%
CSV#shift | 45.630 | 48.476 | 6.2%
CSV.read | 38.527 | 44.661 | 15.9%
CSV.table | 10.293 | 11.247 | 9.3%

## Ruby 2.4.4
  | Before | After | Speed up
-- | -- | -- | --
CSV.foreach | 42.116 | 45.793 | 8.7%
CSV#shift | 43.474 | 46.901 | 7.9%
CSV.read | 37.656 | 40.355 | 7.2%
CSV.table | 10.295 | 10.739 | 4.3%

## Ruby 2.3.7
  | Before | After | Speed up
-- | -- | -- | --
CSV.foreach | 40.263 | 40.450 | 0.5%
CSV#shift | 40.088 | 40.929 | 2.1%
CSV.read | 39.133 | 39.399 | 0.7%
CSV.table | 9.766 | 9.960 | 2.0%

**Comment by kou** [comment]
Thanks.
It looks good.

**Pull request merged**
