### PR TITLE
Update doc links on README

### PR DESCRIPTION
**Pull request by ranjan-purbey**

### CODE REVIEW

**Comment by kou** [comment]
Our documentation is expected to rendered by RDoc not YARD.
FYI: RDoc rendered documentation: https://ruby.github.io/csv/README_md.html

**Comment by ranjan-purbey** [comment]
Sorry but the link in README doesn't work on [Github](https://github.com/ruby/csv) which is set as the homepage on [RubyGems.org](https://rubygems.org/gems/csv)

**Comment by kou** [comment]
GitHub doesn't use RDoc to render our README.

**Comment by ranjan-purbey** [comment]
Can we add https://ruby.github.io/csv/README_md.html in Github about section so that someone new, like me, who comes to the Github repo can find the docs more easily?

**Comment by kou** [comment]
Done.

**Comment by ranjan-purbey** [comment]
Thanks

**Pull request closed without merging**
